Adds Docker BASIS tests
Includes checks whether docker build or tests fails, raising an GitHub action failure

diff --git a/.github/workflows/build-basis.yml b/.github/workflows/build-basis.yml
--- a/.github/workflows/build-basis.yml
+++ b/.github/workflows/build-basis.yml
@@ -1,5 +1,4 @@
-name: Build and test UEDGE - write wheel files if tests pass
-
+name: Builds BASIS UEDGE using Docker
 
 on: [push, pull_request]
 
@@ -11,8 +10,6 @@ jobs:
       fail-fast: false
     steps:
     - uses: actions/checkout@v4
-    - env:
-         BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
     - name: Set UBUNTU tags env variables.
       if: runner.os == 'Linux'
       run: |
@@ -28,10 +25,20 @@ jobs:
           if [[ "${commit_message[1]}" == *"@"*  ]]; then
             echo "spec_tags=${commit_message[1]}" >> $GITHUB_ENV
           fi
-    - name: Test with pytest
+    - name: Build using Docker
       if: ${{ ! contains(env.spec_tags, '@nobasis') }}
+      env:
+        BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
       run: |
         echo $BRANCH_NAME
-        docker run -it --rm fusionbillm/basisuedge checkout $BRANCH_NAME
+        docker run --rm fusionbillm/basisuedge checkout $BRANCH_NAME 2>&1 | tee build.log
+        if [[ ! $( tail -n 50 build.log ) == *"All level 1 tests passed"* ]]; then
+            echo "Docker build and/or level 1 tests failed for BASIS build!"
+            exit 1
+        fi 
+        if [[ ! $( tail -n 50 build.log ) == *"All level 2 tests passed"* ]]; then
+            echo "Docker build and/or level 2 tests failed for BASIS build!"
+            exit 1
+        fi 
 
 
